project_name: CamoDiffusion_ACTK

__base__:
  - config/dataset_ACTK_352x352.yaml

model:
  name: model.net.net
  params:
    num_classes: ${num_channels}
    block_type: 'spiral'

cond_uvit:
  name: model.net.EmptyObject
  params:
    conditioning_klass: model.net.EmptyObject

diffusion_model:
  name: model.SimpleDiffSef.CondGaussianDiffusion
  params:
    image_size: 352
    channels: ${num_channels}
    cond_channels: 1
    num_sample_steps: 10
    pred_objective: 'x0'
    loss_type: 'model.loss.structure_loss_multiclass'

optimizer:
  name: torch.optim.AdamW
  params:
    lr: 1e-4

train_val_forward_fn: "model.train_val_forward.modification_train_val_forward"
# train_val_forward_fn: "model.train_val_forward.simple_train_val_forward"

train_dataset:
  name: dataset.datasets.ACTK_dataset
  params:
    boundary_modification: True

# accelerate launch train_ACTK.py --config config/camoDiff_ACTK_352x352.yaml --num_epoch=100 --batch_size=4 --gradient_accumulate_every=1