project_name: CamoDiffusion_ACTK

__base__:
  - config/dataset_ACTK_352x352.yaml

model:
  name: model.net.net
  params:
    class_num: 4
    mask_chans: 1
    block_type: 'spiral'

cond_uvit:
  name: model.net.EmptyObject
  params:
    conditioning_klass: model.net.EmptyObject

diffusion_model:
  name: model.SimpleDiffSef.CondGaussianDiffusion
  params:
    model: #model
    image_size: 352
    channels: 1
    cond_channels: 1
    noise_d: 64
    num_sample_steps: 10
    clip_sample_denoised: True
    pred_objective: 'x0'
    # loss_type: 'model.loss.structure_loss'
    loss_type: 'model.loss.structure_loss_multiclass'

optimizer:
  name: torch.optim.AdamW
  params:
    lr: 1e-4

train_val_forward_fn: "model.train_val_forward.modification_train_val_forward"
# train_val_forward_fn: "model.train_val_forward.simple_train_val_forward"

train_dataset:
  name: dataset.datasets.ACTK_dataset
  params:
    boundary_modification: True


# accelerate launch train_actk.py --config config/camoDiff_unintegrated_352x352.yaml --num_epoch=150 --batch_size=4 --gradient_accumulate_every=1