train_dataset:
  name: dataset.datasets.ACTK_dataset
  params:
    image_root: './media/ACTK/TrainImage/slices/train'
    gt_root: './media/ACTK/TrainMask/slices/train'
    trainsize: 352

test_dataset:
  ACTK:
    name: dataset.datasets.ACTK_dataset
    params:
      image_root: './media/ACTK/TrainImage/slices/test'
      gt_root: './media/ACTK/TrainMask/slices/test'
      testsize: 352